# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XcDFZHTGM0PCg5RRhBGfozhzp45eaIwf
"""

print("hello")

import seaborn as sns